//==========================================================================
// File Name   : GEO.inc
// Description :
// Written by  : Allen Yeh
// Last modified date:
//              2015/05/29
//==========================================================================
.ifndef __GEO_INC__
.define __GEO_INC__

.external F_GEO_Initial
.external F_GEO_ServiceLoop
.external F_GEO_Resume
.external F_GEO_Pause
.external F_ISR_GEO_PWM_Service
.external F_ISR_GEO_DeltaTime_Service
.external F_GEO_Play
.external F_GEO_Stop
.external F_GEO_Status

.endif
//========================================================================================        
// End of GEO.inc
//========================================================================================