_Group_Table:                     .equ    0       	;Group Index:0           Group Name:Group_Table     Group Type:Unknown 
_Group_Table_Addr:                .equ    0x000130	;Group Addr :0x000130    Group Name:Group_Table     Group Type:Unknown 
_whereareyou_16K_wav:             .equ    0       	;File  Index:0           File  Name:whereareyou_16K_wav.a18 
_whereareyou_16K_wav_Addr:        .equ    0x000130	;File  Addr :0x000130    File  Name:whereareyou_16K_wav.a18 
_vibrate_16K_wav:                 .equ    1       	;File  Index:1           File  Name:vibrate_16K_wav.a18 
_vibrate_16K_wav_Addr:            .equ    0x000b86	;File  Addr :0x000b86    File  Name:vibrate_16K_wav.a18 
_tryme_16K_wav:                   .equ    2       	;File  Index:2           File  Name:tryme_16K_wav.a18 
_tryme_16K_wav_Addr:              .equ    0x00153c	;File  Addr :0x00153c    File  Name:tryme_16K_wav.a18 
_top_16K_wav:                     .equ    3       	;File  Index:3           File  Name:top_16K_wav.a18 
_top_16K_wav_Addr:                .equ    0x00219a	;File  Addr :0x00219a    File  Name:top_16K_wav.a18 
_ten_16K_wav:                     .equ    4       	;File  Index:4           File  Name:ten_16K_wav.a18 
_ten_16K_wav_Addr:                .equ    0x002998	;File  Addr :0x002998    File  Name:ten_16K_wav.a18 
_spin_master_16K_wav:             .equ    5       	;File  Index:5           File  Name:spin_master_16K_wav.a18 
_spin_master_16K_wav_Addr:        .equ    0x0031e6	;File  Addr :0x0031e6    File  Name:spin_master_16K_wav.a18 
_shortpower_16K_wav:              .equ    6       	;File  Index:6           File  Name:shortpower_16K_wav.a18 
_shortpower_16K_wav_Addr:         .equ    0x003d2c	;File  Addr :0x003d2c    File  Name:shortpower_16K_wav.a18 
_shortneighbour_16K_wav:          .equ    7       	;File  Index:7           File  Name:shortneighbour_16K_wav.a18 
_shortneighbour_16K_wav_Addr:     .equ    0x004f02	;File  Addr :0x004f02    File  Name:shortneighbour_16K_wav.a18 
_shortgnd_16K_wav:                .equ    8       	;File  Index:8           File  Name:shortgnd_16K_wav.a18 
_shortgnd_16K_wav_Addr:           .equ    0x005d18	;File  Addr :0x005d18    File  Name:shortgnd_16K_wav.a18 
_shakeneck_16K_wav:               .equ    9       	;File  Index:9           File  Name:shakeneck_16K_wav.a18 
_shakeneck_16K_wav_Addr:          .equ    0x006fb6	;File  Addr :0x006fb6    File  Name:shakeneck_16K_wav.a18 
_shakehead_16K_wav:               .equ    10      	;File  Index:10          File  Name:shakehead_16K_wav.a18 
_shakehead_16K_wav_Addr:          .equ    0x007994	;File  Addr :0x007994    File  Name:shakehead_16K_wav.a18 
_second_16K_wav:                  .equ    11      	;File  Index:11          File  Name:second_16K_wav.a18 
_second_16K_wav_Addr:             .equ    0x00839a	;File  Addr :0x00839a    File  Name:second_16K_wav.a18 
_right_16K_wav:                   .equ    12      	;File  Index:12          File  Name:right_16K_wav.a18 
_right_16K_wav_Addr:              .equ    0x008d50	;File  Addr :0x008d50    File  Name:right_16K_wav.a18 
_release_16K_wav:                 .equ    13      	;File  Index:13          File  Name:release_16K_wav.a18 
_release_16K_wav_Addr:            .equ    0x009576	;File  Addr :0x009576    File  Name:release_16K_wav.a18 
_red_16K_wav:                     .equ    14      	;File  Index:14          File  Name:red_16K_wav.a18 
_red_16K_wav_Addr:                .equ    0x009eb4	;File  Addr :0x009eb4    File  Name:red_16K_wav.a18 
_open_16K_wav:                    .equ    15      	;File  Index:15          File  Name:open_16K_wav.a18 
_open_16K_wav_Addr:               .equ    0x00a6da	;File  Addr :0x00a6da    File  Name:open_16K_wav.a18 
_N010_wav:                        .equ    16      	;File  Index:16          File  Name:N010_wav.a18 
_N010_wav_Addr:                   .equ    0x00af28	;File  Addr :0x00af28    File  Name:N010_wav.a18 
_N009_wav:                        .equ    17      	;File  Index:17          File  Name:N009_wav.a18 
_N009_wav_Addr:                   .equ    0x00b366	;File  Addr :0x00b366    File  Name:N009_wav.a18 
_N008_wav:                        .equ    18      	;File  Index:18          File  Name:N008_wav.a18 
_N008_wav_Addr:                   .equ    0x00b90c	;File  Addr :0x00b90c    File  Name:N008_wav.a18 
_N007_wav:                        .equ    19      	;File  Index:19          File  Name:N007_wav.a18 
_N007_wav_Addr:                   .equ    0x00bd4a	;File  Addr :0x00bd4a    File  Name:N007_wav.a18 
_N006_wav:                        .equ    20      	;File  Index:20          File  Name:N006_wav.a18 
_N006_wav_Addr:                   .equ    0x00c278	;File  Addr :0x00c278    File  Name:N006_wav.a18 
_N005_wav:                        .equ    21      	;File  Index:21          File  Name:N005_wav.a18 
_N005_wav_Addr:                   .equ    0x00c8be	;File  Addr :0x00c8be    File  Name:N005_wav.a18 
_N004_wav:                        .equ    22      	;File  Index:22          File  Name:N004_wav.a18 
_N004_wav_Addr:                   .equ    0x00cdc4	;File  Addr :0x00cdc4    File  Name:N004_wav.a18 
_N003_wav:                        .equ    23      	;File  Index:23          File  Name:N003_wav.a18 
_N003_wav_Addr:                   .equ    0x00d202	;File  Addr :0x00d202    File  Name:N003_wav.a18 
_N002_wav:                        .equ    24      	;File  Index:24          File  Name:N002_wav.a18 
_N002_wav_Addr:                   .equ    0x00d668	;File  Addr :0x00d668    File  Name:N002_wav.a18 
_N001_wav:                        .equ    25      	;File  Index:25          File  Name:N001_wav.a18 
_N001_wav_Addr:                   .equ    0x00da2e	;File  Addr :0x00da2e    File  Name:N001_wav.a18 
_N000_wav:                        .equ    26      	;File  Index:26          File  Name:N000_wav.a18 
_N000_wav_Addr:                   .equ    0x00de94	;File  Addr :0x00de94    File  Name:N000_wav.a18 
_left_16K_wav:                    .equ    27      	;File  Index:27          File  Name:left_16K_wav.a18 
_left_16K_wav_Addr:               .equ    0x00e3c2	;File  Addr :0x00e3c2    File  Name:left_16K_wav.a18 
_iamcoming_16K_wav:               .equ    28      	;File  Index:28          File  Name:iamcoming_16K_wav.a18 
_iamcoming_16K_wav_Addr:          .equ    0x00ec38	;File  Addr :0x00ec38    File  Name:iamcoming_16K_wav.a18 
_horseshoe_singlecn:              .equ    29      	;File  Index:29          File  Name:horseshoe_singlecn.a18 
_horseshoe_singlecn_Addr:         .equ    0x00f77e	;File  Addr :0x00f77e    File  Name:horseshoe_singlecn.a18 
_horseshoe:                       .equ    30      	;File  Index:30          File  Name:horseshoe.a18 
_horseshoe_Addr:                  .equ    0x01475c	;File  Addr :0x01475c    File  Name:horseshoe.a18 
_horseloud:                       .equ    31      	;File  Index:31          File  Name:horseloud.a18 
_horseloud_Addr:                  .equ    0x01973a	;File  Addr :0x01973a    File  Name:horseloud.a18 
_hold_16K_wav:                    .equ    32      	;File  Index:32          File  Name:hold_16K_wav.a18 
_hold_16K_wav_Addr:               .equ    0x01a6e0	;File  Addr :0x01a6e0    File  Name:hold_16K_wav.a18 
_hello_16K_wav:                   .equ    33      	;File  Index:33          File  Name:hello_16K_wav.a18 
_hello_16K_wav_Addr:              .equ    0x01af7e	;File  Addr :0x01af7e    File  Name:hello_16K_wav.a18 
_green_16K_wav:                   .equ    34      	;File  Index:34          File  Name:green_16K_wav.a18 
_green_16K_wav_Addr:              .equ    0x01b7f4	;File  Addr :0x01b7f4    File  Name:green_16K_wav.a18 
_gentleman_16K_wav:               .equ    35      	;File  Index:35          File  Name:gentleman_16K_wav.a18 
_gentleman_16K_wav_Addr:          .equ    0x01c092	;File  Addr :0x01c092    File  Name:gentleman_16K_wav.a18 
_explore_16K_wav:                 .equ    36      	;File  Index:36          File  Name:explore_16K_wav.a18 
_explore_16K_wav_Addr:            .equ    0x01ca48	;File  Addr :0x01ca48    File  Name:explore_16K_wav.a18 
_everythingok_16K_wav:            .equ    37      	;File  Index:37          File  Name:everythingok_16K_wav.a18 
_everythingok_16K_wav_Addr:       .equ    0x01d426	;File  Addr :0x01d426    File  Name:everythingok_16K_wav.a18 
_EN_Z_16K_wav:                    .equ    38      	;File  Index:38          File  Name:EN_Z_16K_wav.a18 
_EN_Z_16K_wav_Addr:               .equ    0x01e19c	;File  Addr :0x01e19c    File  Name:EN_Z_16K_wav.a18 
_EN_Y_16K_wav:                    .equ    39      	;File  Index:39          File  Name:EN_Y_16K_wav.a18 
_EN_Y_16K_wav_Addr:               .equ    0x01e562	;File  Addr :0x01e562    File  Name:EN_Y_16K_wav.a18 
_EN_X_16K_wav:                    .equ    40      	;File  Index:40          File  Name:EN_X_16K_wav.a18 
_EN_X_16K_wav_Addr:               .equ    0x01e8b0	;File  Addr :0x01e8b0    File  Name:EN_X_16K_wav.a18 
_EN_W_16K_wav:                    .equ    41      	;File  Index:41          File  Name:EN_W_16K_wav.a18 
_EN_W_16K_wav_Addr:               .equ    0x01ecc6	;File  Addr :0x01ecc6    File  Name:EN_W_16K_wav.a18 
_EN_V_16K_wav:                    .equ    42      	;File  Index:42          File  Name:EN_V_16K_wav.a18 
_EN_V_16K_wav_Addr:               .equ    0x01f104	;File  Addr :0x01f104    File  Name:EN_V_16K_wav.a18 
_EN_U_16K_wav:                    .equ    43      	;File  Index:43          File  Name:EN_U_16K_wav.a18 
_EN_U_16K_wav_Addr:               .equ    0x01f4ca	;File  Addr :0x01f4ca    File  Name:EN_U_16K_wav.a18 
_EN_T_16K_wav:                    .equ    44      	;File  Index:44          File  Name:EN_T_16K_wav.a18 
_EN_T_16K_wav_Addr:               .equ    0x01f818	;File  Addr :0x01f818    File  Name:EN_T_16K_wav.a18 
_EN_S_16K_wav:                    .equ    45      	;File  Index:45          File  Name:EN_S_16K_wav.a18 
_EN_S_16K_wav_Addr:               .equ    0x01fb8e	;File  Addr :0x01fb8e    File  Name:EN_S_16K_wav.a18 
_EN_R_16K_wav:                    .equ    46      	;File  Index:46          File  Name:EN_R_16K_wav.a18 
_EN_R_16K_wav_Addr:               .equ    0x01ff54	;File  Addr :0x01ff54    File  Name:EN_R_16K_wav.a18 
_EN_Q_16K_wav:                    .equ    47      	;File  Index:47          File  Name:EN_Q_16K_wav.a18 
_EN_Q_16K_wav_Addr:               .equ    0x020342	;File  Addr :0x020342    File  Name:EN_Q_16K_wav.a18 
_EN_P_16K_wav:                    .equ    48      	;File  Index:48          File  Name:EN_P_16K_wav.a18 
_EN_P_16K_wav_Addr:               .equ    0x020730	;File  Addr :0x020730    File  Name:EN_P_16K_wav.a18 
_EN_O_16K_wav:                    .equ    49      	;File  Index:49          File  Name:EN_O_16K_wav.a18 
_EN_O_16K_wav_Addr:               .equ    0x020a7e	;File  Addr :0x020a7e    File  Name:EN_O_16K_wav.a18 
_EN_N_16K_wav:                    .equ    50      	;File  Index:50          File  Name:EN_N_16K_wav.a18 
_EN_N_16K_wav_Addr:               .equ    0x020d2c	;File  Addr :0x020d2c    File  Name:EN_N_16K_wav.a18 
_EN_M_16K_wav:                    .equ    51      	;File  Index:51          File  Name:EN_M_16K_wav.a18 
_EN_M_16K_wav_Addr:               .equ    0x02107a	;File  Addr :0x02107a    File  Name:EN_M_16K_wav.a18 
_EN_L_16K_wav:                    .equ    52      	;File  Index:52          File  Name:EN_L_16K_wav.a18 
_EN_L_16K_wav_Addr:               .equ    0x0213c8	;File  Addr :0x0213c8    File  Name:EN_L_16K_wav.a18 
_EN_K_16K_wav:                    .equ    53      	;File  Index:53          File  Name:EN_K_16K_wav.a18 
_EN_K_16K_wav_Addr:               .equ    0x0216ee	;File  Addr :0x0216ee    File  Name:EN_K_16K_wav.a18 
_EN_J_16K_wav:                    .equ    54      	;File  Index:54          File  Name:EN_J_16K_wav.a18 
_EN_J_16K_wav_Addr:               .equ    0x021a64	;File  Addr :0x021a64    File  Name:EN_J_16K_wav.a18 
_EN_I_16K_wav:                    .equ    55      	;File  Index:55          File  Name:EN_I_16K_wav.a18 
_EN_I_16K_wav_Addr:               .equ    0x021e7a	;File  Addr :0x021e7a    File  Name:EN_I_16K_wav.a18 
_EN_H_16K_wav:                    .equ    56      	;File  Index:56          File  Name:EN_H_16K_wav.a18 
_EN_H_16K_wav_Addr:               .equ    0x022128	;File  Addr :0x022128    File  Name:EN_H_16K_wav.a18 
_EN_G_16K_wav:                    .equ    57      	;File  Index:57          File  Name:EN_G_16K_wav.a18 
_EN_G_16K_wav_Addr:               .equ    0x022566	;File  Addr :0x022566    File  Name:EN_G_16K_wav.a18 
_EN_F_16K_wav:                    .equ    58      	;File  Index:58          File  Name:EN_F_16K_wav.a18 
_EN_F_16K_wav_Addr:               .equ    0x022904	;File  Addr :0x022904    File  Name:EN_F_16K_wav.a18 
_EN_E_16K_wav:                    .equ    59      	;File  Index:59          File  Name:EN_E_16K_wav.a18 
_EN_E_16K_wav_Addr:               .equ    0x022c7a	;File  Addr :0x022c7a    File  Name:EN_E_16K_wav.a18 
_EN_D_16K_wav:                    .equ    60      	;File  Index:60          File  Name:EN_D_16K_wav.a18 
_EN_D_16K_wav_Addr:               .equ    0x022fa0	;File  Addr :0x022fa0    File  Name:EN_D_16K_wav.a18 
_EN_C_16K_wav:                    .equ    61      	;File  Index:61          File  Name:EN_C_16K_wav.a18 
_EN_C_16K_wav_Addr:               .equ    0x023316	;File  Addr :0x023316    File  Name:EN_C_16K_wav.a18 
_EN_B_16K_wav:                    .equ    62      	;File  Index:62          File  Name:EN_B_16K_wav.a18 
_EN_B_16K_wav_Addr:               .equ    0x02372c	;File  Addr :0x02372c    File  Name:EN_B_16K_wav.a18 
_EN_A_16K_wav:                    .equ    63      	;File  Index:63          File  Name:EN_A_16K_wav.a18 
_EN_A_16K_wav_Addr:               .equ    0x023aa2	;File  Addr :0x023aa2    File  Name:EN_A_16K_wav.a18 
_Di_16K_wav:                      .equ    64      	;File  Index:64          File  Name:Di_16K_wav.a18 
_Di_16K_wav_Addr:                 .equ    0x023d78	;File  Addr :0x023d78    File  Name:Di_16K_wav.a18 
_comehere_16K_wav:                .equ    65      	;File  Index:65          File  Name:comehere_16K_wav.a18 
_comehere_16K_wav_Addr:           .equ    0x023df6	;File  Addr :0x023df6    File  Name:comehere_16K_wav.a18 
_close_16K_wav:                   .equ    66      	;File  Index:66          File  Name:close_16K_wav.a18 
_close_16K_wav_Addr:              .equ    0x0247d4	;File  Addr :0x0247d4    File  Name:close_16K_wav.a18 
_click_16K_wav:                   .equ    67      	;File  Index:67          File  Name:click_16K_wav.a18 
_click_16K_wav_Addr:              .equ    0x02509a	;File  Addr :0x02509a    File  Name:click_16K_wav.a18 
_button_16K_wav:                  .equ    68      	;File  Index:68          File  Name:button_16K_wav.a18 
_button_16K_wav_Addr:             .equ    0x025870	;File  Addr :0x025870    File  Name:button_16K_wav.a18 
_box_open_16K_wav:                .equ    69      	;File  Index:69          File  Name:box_open_16K_wav.a18 
_box_open_16K_wav_Addr:           .equ    0x025b1e	;File  Addr :0x025b1e    File  Name:box_open_16K_wav.a18 
_box_close_16K_wav:               .equ    70      	;File  Index:70          File  Name:box_close_16K_wav.a18 
_box_close_16K_wav_Addr:          .equ    0x026574	;File  Addr :0x026574    File  Name:box_close_16K_wav.a18 
_bottom_16K_wav:                  .equ    71      	;File  Index:71          File  Name:bottom_16K_wav.a18 
_bottom_16K_wav_Addr:             .equ    0x02706a	;File  Addr :0x02706a    File  Name:bottom_16K_wav.a18 
_blue_16K_wav:                    .equ    72      	;File  Index:72          File  Name:blue_16K_wav.a18 
_blue_16K_wav_Addr:               .equ    0x0278b8	;File  Addr :0x0278b8    File  Name:blue_16K_wav.a18 
_batvol_16K_wav:                  .equ    73      	;File  Index:73          File  Name:batvol_16K_wav.a18 
_batvol_16K_wav_Addr:             .equ    0x02808e	;File  Addr :0x02808e    File  Name:batvol_16K_wav.a18 
_animal_angry:                    .equ    74      	;File  Index:74          File  Name:animal_angry.a18 
_animal_angry_Addr:               .equ    0x028f94	;File  Addr :0x028f94    File  Name:animal_angry.a18 
